source 'https://rubygems.org'

gem 'activerecord', '~> 4.2.5'
gem 'builder', '~> 3.2'
gem 'mime-types', '~> 3.1'
gem 'mini_magick', '~> 4.5'
gem 'rack', '~> 1.6'
gem 'rack_csrf', '~> 2.5'
gem 'sinatra', '~> 1.4'
gem 'sinatra-cross_origin', '~> 0.3'
gem 'sinatra-flash', '~> 0.3'
gem 'sqlite3', '~> 1.3'
